import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import i18next from 'eslint-plugin-i18next'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

// Mirrors apps/web/eslint.config.js so both apps are held to the same bar.
// Two deliberate differences, each because the web rule does not apply here:
//
//  - No react-refresh. Web uses reactRefresh.configs.vite, which encodes Vite's
//    HMR boundary rules. Metro's Fast Refresh has different constraints, so the
//    Vite variant would report violations that mean nothing on native.
//
//  - Globals are browser + node rather than browser alone. React Native exposes
//    a browser-like set (fetch, console, timers) and the vitest suites run on
//    Node.
export default defineConfig([
  globalIgnores([
    'dist',
    'coverage',
    '.expo',
    'node_modules',
    // Generated by `expo prebuild` — disposable output, not source.
    'ios',
    'android',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      i18next,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Same internationalization bar as web: no hardcoded strings in markup.
      // Keep the ignore lists in sync with apps/web/eslint.config.js.
      'i18next/no-literal-string': ['error', {
        markupOnly: true,
        ignoreAttribute: [
          // Component/HTML attributes that should allow literals
          'className', 'style', 'type', 'id', 'name',
          'data-testid', 'data-*', 'aria-*',
          'role', 'htmlFor', 'for',
          // React Router
          'to', 'path',
          // Form attributes
          'method', 'action', 'encType',
        ],
        ignoreCallee: [
          'console.error', 'console.log', 'console.warn', 'console.info',
        ],
        ignore: [
          /^[0-9]+$/, // Pure numbers
          /^[A-Z]{1,3}$/, // Single letters or short acronyms (ID, USD, etc)
          /^[.,;:!?()[\]{}<>'"`~@#$%^&*+=|\\/\-_]+$/, // Punctuation only
        ],
      }],
    },
  },
  {
    // Test fixtures are not user-facing, so the no-hardcoded-strings rule does
    // not apply: a test that renders <Text>count 0</Text> and asserts on that
    // exact string is clearer than one indirecting through the locale file, and
    // routing it through t() would couple the assertion to translations it is
    // not testing. apps/web never needed this exemption because its tests render
    // app components rather than declaring their own JSX text.
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      'i18next/no-literal-string': 'off',
    },
  },
])
